### ISSUE TITLE
Project Activity

### ISSUE THREAD

**Issue by Helixable** [DaveDuck321/KahootSmasher#9]
Hello Dave. I like your project a lot. I would like to help in the development of this project. I'm not sure if this is inactive though. Please email me here: noahgerardv@gmail.com

**Comment by DaveDuck321** [comment]
I've emailed you explaining the situation. The activity for the project is as follows

- [SmashIt](https://github.com/DaveDuck321/SmashIt) -- Active bug fixes
- [KahootSmasher-NodeJS](https://github.com/DaveDuck321/KahootSmasher-NodeJS) -- Active major bug fixes
- [KahootSmasher](https://github.com/DaveDuck321/KahootSmasher) -- Undecided, depends on interest
